### ISSUE TITLE
RUSTSEC-2020-0071 lists unknown platforms

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#1053]
[RUSTSEC-2020-0071](https://github.com/rustsec/advisory-db/blob/main/crates/time/RUSTSEC-2020-0071.md) lists a large number of platforms, some of this are unrecognized by `platforms` crate and end up being treated as unknown by RustSec tooling. For example, [the OSV exported version of this advisory](https://github.com/rustsec/advisory-db/blob/osv/crates/RUSTSEC-2020-0071.json) contains the string "unknown" in the list of platforms several times.

We should consider implementing a checks for this in `rustsec-admin lint`.

**Comment by pinkforest** [comment]
Following up in here properly:
https://github.com/rustsec/rustsec/issues/671

Closing this in favor of tooling ticket in rustsec/rustsec
