### ISSUE TITLE
make `serde` safe

### ISSUE THREAD

**Issue by bkontur** [rustsec/advisory-db#1065]
Hi guys,

please, I just want to ask, could https://github.com/serde-rs/serde/issues/2096 be relevant from your point if view?
is it something, which could be easily fixed? or does it make even sense?
Thank you for any response :)

**Comment by Shnatsel** [comment]
This is better suited for https://github.com/rust-secure-code/safety-dance than here. I'm going to close this since it's not relevant to the advisory DB, but you're welcome to file an issue on the safety-dance repo.

**Comment by bkontur** [comment]
@Shnatsel 
aha, ok, ok, thank you, I opened issue there: https://github.com/rust-secure-code/safety-dance/issues/74
