### ISSUE TITLE
Unsigned commit is breaking cargo audit

### ISSUE THREAD

**Issue by danrspencer** [rustsec/advisory-db#1070]
The latest commit to the repo has broken `cargo audit`:

```
error: couldn't fetch advisory database: git operation failed: no signature on commit 76105bde909f209cf1c9edbd58b3993e79629c8a: Assigned RUSTSEC-2020-0158 to slice-deque (#1069) (github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>)
```

**Comment by alex** [comment]
I think I fixed this with https://github.com/rustsec/advisory-db/commit/b426bdf91ca4e84bb67d55d0ef21d4ddbd514503

Sorry about that, it's unclear why that commit was not signed.
