### ISSUE TITLE
`sodiumoxide` is (semi-)unmaintained

### ISSUE THREAD

**Issue by tarcieri** [rustsec/advisory-db#1090]
See https://github.com/sodiumoxide/sodiumoxide/commit/5bb1dfd2578539b89ffb0cbea25f21f00cfb963e#commitcomment-58111537

I asked @dnaq on that issue about whether we should file an unmaintained crate advisory for it, because unlike the crates we typically file advisories for it sounds like security-related fixes will be included/released. I think we're both a bit unclear on if it makes sense here.

I am starting to lean towards filing an advisory just because `sodiumoxide` has historically been a go-to solution for Rust cryptography and is still widely used (1,500-2,000 downloads per day). I was [recommending `sodiumoxide` as far back as 2014](https://speakerdeck.com/tarcieri/thoughts-on-rust-cryptography?slide=84).

It would be nice to point people at alternatives, however I don't know what good alternatives are. The `rust_sodium` crate is unmaintained, for example. There are also placeholder `sodium` and `libsodium` crates.

I know @jedisct1 has a [fork of `libsodium-sys`](https://github.com/jedisct1/libsodium-sys-stable).

There are also various pure Rust crates that implement NaCl protocols, such as [`xsalsa20poly1305`](https://github.com/RustCrypto/AEADs/tree/master/xsalsa20poly1305), the @RustCrypto [nacl-compat](https://github.com/RustCrypto/nacl-compat) crates, and [`dryoc`](https://crates.io/crates/dryoc).

I think if we can come up with some actionable advice for what current users of `sodiumoxide` should migrate to, it would make sense to file an unmaintained crate advisory.

**Comment by tarcieri** [comment]
@Dylan-DPC it sounds like you're interested in maintaining a `sodiumoxide` fork?

**Comment by Dylan-DPC** [comment]
Yes. Given it is used in many places and there aren't alternatives that do
everything, it would make sense.

I'm a comaintainer and also have admin permissions on the org so it should
be easy to continue with the crate with a new team.

**Comment by dnaq** [comment]
@Dylan-DPC I do not mean this in any snarky way at all, but as you say you have been co-maintainer for many years and you have seen the discussions about deprecating the library and didn’t say anything at all back then.

Not trying to diminish the things you have done for the project in any way, in the beginning when we moved to a community maintained model the work you were doing was instrumental in getting the project going, but you haven’t taken an active part in maintaining the project for a couple of years.

If you wish to take over maintainership, then by all means you’re welcome to it, but if we end up at a point where exactly nothing happens again then we won’t have gained anything really.

**Comment by pinkforest** [comment]
sodiumoxide is having some recent movement re: maintenance fixes
https://github.com/sodiumoxide/sodiumoxide/pull/478#issuecomment-1193795915
