### ISSUE TITLE
`ansi_term` appears unmaintained

### ISSUE THREAD

**Issue by GeorgeHahn** [rustsec/advisory-db#1095]
A [maintenance inquiry](https://github.com/ogham/rust-ansi-term/issues/72) has been open since August 2021 without response. The most recent release & PR merge was in September 2019 and multiple PRs + issues are outstanding.

**Comment by pinkforest** [comment]
Please feel free to send a PR - it doesn't have much dependencies but it has unsafe block someone has sent a PR on.

**Comment by pinkforest** [comment]
Do we have any alternatives to recommend if we were to mark this unmaintained ?

There is like nu-ansi-term ? Wonder what else is out there ?

**Comment by joshtriplett** [comment]
I have permission to upload the crate on crates.io, but not permission to move the repository to some other organization, and in any case I don't have plans to do ongoing maintenance of ansi_term myself. I would personally recommend using the anstyle family of crates at this point, maintained by @epage.

**Comment by epage** [comment]
Note that [`anstyle`](https://github.com/epage/anstyle) is still fairly early.  All it supports at the moment is ansi style descriptions independent of the term styling crate so it can be used in public APIs for stylesheets while the underlying term styler can change (and it hasn't been vetted yet for a 1.0).  https://github.com/epage/anstyle/issues/5 is tracing creating of streams for formatting.  As for timeline, this is my expected focus area after clap 4.0.0.

**Comment by pinkforest** [comment]
Thanks team -

I've got a nudge going here: https://github.com/rustsec/advisory-db/pull/1372

If anyone comes up additional possible alternative(s) - 

I've also added yansi to the list by @SergioBenitez

**Comment by SergioBenitez** [comment]
I have an upgrade coming to yansi that I'm really excited about that  resolves effectively every personal qualm as well as (I believe) every concern that @epage has raised about the library in the past. Happy to share more if there's interest!
