### ISSUE TITLE
serde_cbor is unmaintained

### ISSUE THREAD

**Issue by jcaden** [rustsec/advisory-db#1110]
As you can see from the project description in the crates.io page and the readme in the repository, the project is not maintained anymore.
https://github.com/pyfisch/cbor
https://crates.io/crates/serde_cbor

The project was looking for maintainers: https://github.com/pyfisch/cbor/issues/179
But it looks like the repository is archived now, so it's not possible interaction with the author via Github.

**Comment by tarcieri** [comment]
I'd agree this crate falls under our unmaintained crate policy as it clearly states it's unmaintained and the repo is archived.

Can you open a PR with an unmaintained crate advisory?

**Comment by jcaden** [comment]
Here is the PR https://github.com/rustsec/advisory-db/pull/1114

**Comment by tarcieri** [comment]
Thanks! Assigned `RUSTSEC-2021-0127` in #1115
