### ISSUE TITLE
Memory corruption in `utf16_lit` v2.0.2

### ISSUE THREAD

**Issue by poliorcetics** [rustsec/advisory-db#1147]
Do something like this:

```rust
#[inline(never)]
fn test_fn() -> *const u16 {
    utf16_lit::utf16_null!("SHA256").as_ptr()
}

#[inline(never)]
fn test_fn2() -> *const u16 {
    let a = utf16_lit::utf16_null!("SHA256");
    dbg!(&a);
    a.as_ptr()
}

fn debugger(mut p: *const u16) {
    println!("{:?}", p);
    let mut v = Vec::new();
    for _ in 0..7 {
        v.push(unsafe { *p });
        dbg!(&v);
        p = unsafe { p.add(1) };
    }
    let _ = dbg!(String::from_utf16(&v));
}

fn main() {
    let test = test_fn();
    let test2 = test_fn2();
    debugger(test);
    debugger(test2);    
}
```

WIth `utf16_lit` as the only dependency, this gives me the following when using `cargo run`:

```
[src/main.rs:9] &a = [
    83,
    72,
    65,
    50,
    53,
    54,
    0,
]
0x55b43e36f18a
[src/main.rs:18] &v = [
    83,
]
[src/main.rs:18] &v = [
    83,
    72,
]
[src/main.rs:18] &v = [
    83,
    72,
    65,
]
[src/main.rs:18] &v = [
    83,
    72,
    65,
    50,
]
[src/main.rs:18] &v = [
    83,
    72,
    65,
    50,
    53,
]
[src/main.rs:18] &v = [
    83,
    72,
    65,
    50,
    53,
    54,
]
[src/main.rs:18] &v = [
    83,
    72,
    65,
    50,
    53,
    54,
    0,
]
[src/main.rs:21] String::from_utf16(&v) = Ok(
    "SHA256\u{0}",
)
0x7ffee53471aa
[src/main.rs:18] &v = [
    15927,
]
[src/main.rs:18] &v = [
    15927,
    21940,
]
[src/main.rs:18] &v = [
    15927,
    21940,
    0,
]
[src/main.rs:18] &v = [
    15927,
    21940,
    0,
    24432,
]
[src/main.rs:18] &v = [
    15927,
    21940,
    0,
    24432,
    15923,
]
[src/main.rs:18] &v = [
    15927,
    21940,
    0,
    24432,
    15923,
    21940,
]
[src/main.rs:18] &v = [
    15927,
    21940,
    0,
    24432,
    15923,
    21940,
    0,
]
[src/main.rs:21] String::from_utf16(&v) = Ok(
    "㸷喴\u{0}彰㸳喴\u{0}",
)
```

Note the two addresses are very different so it's not because there was overlap: `0x55b43e36f18a` and `0x7ffee53471aa`.

Moving `debugger(test)` directly below `let test = ...` fixes the problem, commenting out the call to `test_fn` and the `debugger` line associated to it fixes the problem, and probably other small changes fix the problem.

That's very brittle behavior.

I *think* this is due to the use of `const`s and not `static`s in the macro, since `const`s are basically copy pasted into their use point, which leads to loss of the lifetime through `as_ptr` which leads to `rustc` just saying "this is never used, don't initialize it" and so the data behind the array becomes random things that are here by chance.

Inlining seems to save the day in `test_fn` but a more heavy use breaks it.

*First issue here, sorry if I missed something while reading the instructions*

**Comment by Shnatsel** [comment]
Thank you for the report!

Generally these kinds of issues should be reported to the issue tracker for the crate. I see you have cross-referenced it there; I believe that is sufficient in this case, but please open an issue on the crate issue tracker in the future.

**Comment by poliorcetics** [comment]
Ah, I should have done the reverse, a full issue on the crate and a link here ?

**Comment by dtolnay** [comment]
I definitely don't think it's fair to characterize this as memory corruption in utf16_lit. That's like saying the following macro corrupts memory:

```rust
macro_rules! zero_array {
    () => { [0u8; 100] };
}
```

because if someone were to write the following then they get nonzero outputs:

```rust
fn test_fn() -> *const u8 {
    let array = zero_array!();
    array.as_ptr()
}

fn main() {
    println!("{:?}", unsafe { &*(test_fn() as *const [u8; 100]) });
}
```

Nope, the stack-use-after-return is in your downstream unsafe code. If you use utf16_lit [as documented](https://docs.rs/utf16_lit/2.0.2/utf16_lit/) (which does not involve any `unsafe`) then your code is correct.

I think this is true independent of whether there's a possible API or implementation change in utf16_lit that would produce defined behavior for the original broken unsafe code. I wouldn't want a memory corruption advisory on utf16_lit unless they are corrupting memory, not some unsafe code elsewhere that they aren't responsible for.

**Comment by poliorcetics** [comment]
Closing since you all have convinced me it was a mistake on my part, not a misdesign on the crate side.

Sorry for the noise and sorry @Lokathor for Rustsec scare !
