### ISSUE TITLE
`prettytables-rs` is abandoned

### ISSUE THREAD

**Issue by Nukesor** [rustsec/advisory-db#1173]
The `prettytables-rs` [library](https://github.com/phsym/prettytable-rs) has been abandoned.
There's been no active development since roughly three years and the author hasn't been reachable as well.

There exists an [open PR](https://github.com/phsym/prettytable-rs/pull/138) and an [open ticket](https://github.com/phsym/prettytable-rs/issues/139) to mark the crate as deprecated/abandoned, but the author has not answered on either yet.

There hasn't been any comments of the crate's maintainer on any other issue since several years either.

**Comment by Nukesor** [comment]
Ping @phsym

**Comment by pinkforest** [comment]
Thanks for caring and following up. 

I have additionally sent an e-mail to the maintainer - the maintainer seems to have had some activity a week ago

As per recent policy change if the maintainer does not answer in 90 days we might merge this if we don't get any clarification re: maintenance policy for security fixes or maintenance handover potential.

**Comment by pinkforest** [comment]
The maintainer has responded to myself and is keen to either merge security fixes or hand over the crate.

**Comment by Nukesor** [comment]
In that case, I'm just going to close this issue :)

I see that this isn't a security issue per-se (yet). I'm still a bit curious why the author doesn't take care of this project since this many years without properly abandoning it or at least flagging it as unmaintained, but I guess that's not for me to decide.
