### ISSUE TITLE
`pty` has been abandoned

### ISSUE THREAD

**Issue by Nukesor** [rustsec/advisory-db#1212]
The [pty](https://github.com/hibariya/pty-rs) crate seems to be abandoned.

The author of the crate has been pinged at Oct 28, 2018 and didn't respond up until now:
https://github.com/hibariya/pty-rs/issues/19

**Comment by tarcieri** [comment]
I would agree this crate meets our policy for unmaintained crates. Feel free to file an advisory for it.
