### ISSUE TITLE
`cell-project` is unsound

### ISSUE THREAD

**Issue by SoniEx2** [rustsec/advisory-db#1226]
`cell-project` uses the wrong variance and is unsound.

**Comment by Shnatsel** [comment]
Is the issue reported upstream? That would be the first step to fixing it.

**Comment by pinkforest** [comment]
Seems @RustyYato merged your fix :+1:
https://github.com/RustyYato/cell-project/pull/4#issuecomment-1208108266

@RustyYato I assume there is new version in crates.io soon ?

Probably might be good to yank the old versions if it is feasible as well.

Cheers

**Comment by SoniEx2** [comment]
@pinkforest it is done!

**Comment by pinkforest** [comment]
@RustyYato would you like to send `informational = unsound` PR for this ?

**Comment by RustyYato** [comment]
Sure, I can do that
