### ISSUE TITLE
Add advisory for pkcs11

### ISSUE THREAD

**Issue by 5225225** [rustsec/advisory-db#1280]
The crate hasn't been touched in 2 years, and seems to have a fair few possibly security-related open issues.

https://github.com/mheese/rust-pkcs11/issues/55
https://github.com/mheese/rust-pkcs11/issues/54
https://github.com/mheese/rust-pkcs11/issues/49
https://github.com/mheese/rust-pkcs11/pull/53

I can't quite work out *what* to mark as the advisory, and don't know the crate well enough to explain these issues.

**Comment by tarcieri** [comment]
It might qualify as unmaintained. See our policy/process here: https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

**Comment by ionut-arm** [comment]
I've raised [an issue](https://github.com/mheese/rust-pkcs11/issues/57) on the repo, we can wait and see if we get a reply :)

**Comment by 5225225** [comment]
If you're more familiar with the memory safety issues @ionut-arm maybe you could write / help me write the advisory (by listing/explaining the distinct issues with it so I can list em)?

Since "this is unmaintained" isn't the *only* issue with it.

**Comment by 5225225** [comment]
I think a draft PR that you can tag me in to look over would be fine (so other people can look over it too). I'm AFK at the moment but can check over it in 2ish hours.

**Comment by 5225225** [comment]
Done in #1282
