### ISSUE TITLE
anymap is maintained now

### ISSUE THREAD

**Issue by aminya** [rustsec/advisory-db#1281]
https://github.com/chris-morgan/anymap

This advisory is outdated 
https://rustsec.org/advisories/RUSTSEC-2021-0065

**Comment by Shnatsel** [comment]
The latest version on crates.io is still "0.12.1", published 5 years ago, and includes a soundness bug as discussed in the advisory. We'll gladly retract the advisory once a fixed version is released to crates.io.

**Comment by pinkforest** [comment]
Closing this for now - if the situation changes please feel free to re-open.
