### ISSUE TITLE
DoS vulnerabilities in juniper and async-graphql

### ISSUE THREAD

**Issue by djc** [rustsec/advisory-db#1285]
https://github.com/async-graphql/async-graphql/security/advisories/GHSA-xq3c-8gqm-v648

https://github.com/graphql-rust/juniper/security/advisories/GHSA-4rx6-g5vg-5f3j

**Comment by djc** [comment]
Unfortunately the fix release for async-graphql is not yet published:

https://github.com/async-graphql/async-graphql/discussions/1000

**Comment by pinkforest** [comment]
Great - Thanks good catch - Apparently async-graphql patched published now

Feel free to send a PR or I can do later

**Comment by pinkforest** [comment]
This was merged #1290
