### ISSUE TITLE
Double escaping in rustsec web pages

### ISSUE THREAD

**Issue by alex** [RustSec/advisory-db#130]
Example:
https://rustsec.org/advisories/RUSTSEC-2019-0005.html

`&str` is rendered as `&amp;str`

**Comment by tarcieri** [comment]
Looks like the Markdown generator is double escaping it:

https://github.com/RustSec/rustsec.github.io/blame/4d1907c9fb/_posts/2019-06-15-RUSTSEC-2019-0005.md#L11

**Comment by tarcieri** [comment]
It should just be a Handlebars config option:

https://github.com/RustSec/rustsec.github.io/blob/master/rustsec-website-gen/src/main.rs#L96
https://docs.rs/handlebars/2.0.1/handlebars/struct.Handlebars.html#method.register_escape_fn

e.g.

```rust
handlebars.register_escape_fn(handlebars::no_escape);
```

**Comment by notriddle** [comment]
If you're using handlebars, the output of your markdown parser should be written using `{{{html}}}`.

For example, [here](https://github.com/notriddle/more-interesting/blob/e7b1c15f11d0a7dba550355ae628d04d702bc605/templates/index.hbs#L19) where `{{score}}` is subject to escaping while `{{{excerpt_html}}}` is not.

**Comment by tarcieri** [comment]
These have been re-rendered after merging @notriddle's PR https://github.com/RustSec/rustsec.github.io/pull/7 and are no-longer double escaped
