### ISSUE TITLE
Latest commits are not signed, breaking downstream CI

### ISSUE THREAD

**Issue by Bromeon** [rustsec/advisory-db#1307]
The last commit https://github.com/rustsec/advisory-db/commit/db78ca0149f8ed7c8c2d2aea0236edb63a23f362 seems to break some CI integrations, because it's not a verified committer.

`cargo-deny` fails to fetch the advisory database, with error:
```
> cargo deny check --config tools/deny.toml
[ERROR] failed to fetch advisory database: git operation failed: no signature on commit db78ca0149f8ed7c8c2d2aea0236edb63a23f362: Revert "Adopt rust-admin 0.8.0 --skip-namecheck rustdecimal" (pinkforest <36498018+pinkforest@users.noreply.github.com>)
Error: Process completed with exit code 1.
```

See e.g. [this CI run](https://github.com/Bromeon/godot-rust/runs/7678284796?check_suite_focus=true).

**Comment by Bromeon** [comment]
Thanks for the fast fix in https://github.com/rustsec/advisory-db/commit/d87417aea06584378609bdfc683a41de14f36acc 🚀

**Comment by tarcieri** [comment]
@pinkforest FYI, everything needs to go through a PR workflow

I went ahead and enabled "include administrators" in the branch protections

**Comment by Shnatsel** [comment]
Also the requirement for the commit to be signed is useless; I've filed https://github.com/rustsec/rustsec/issues/629 to remove it.

**Comment by pinkforest** [comment]
Yeah this was my stuff up :woman_shrugging: my apologies :sob: - I don't typically like working in branch-in-origin-repo - I had pulled the .git from https:// instead of git:// and was working in the rustdecimal branch and had to switch to the git:// and then forgot to change the branch again.

As to salt to the wounds that branch would require rebase so I went with another PR

**Comment by 8573** [comment]
> had to switch to the git://

Huh, under what circumstances would you have _had to_ use the unsecured “git://” protocol? Do you mean “git+ssh://”?
