### ISSUE TITLE
`parity-util-mem` soundness

### ISSUE THREAD

**Issue by pinkforest** [rustsec/advisory-db#1399]
Came across while investigating this: https://github.com/rustsec/advisory-db/issues/1394

https://github.com/paritytech/parity-common/issues/364

Both Github repository and crates.io readme contains a big warning:
https://github.com/paritytech/parity-common/tree/master/parity-util-mem
https://crates.io/crates/parity-util-mem

Cheers

**Comment by pinkforest** [comment]
Seems the crate is not getting any updates anymore: https://github.com/paritytech/substrate/issues/12658
And there is movement away from it. Probably best to flag unmaintained on it.

**Comment by ordian** [comment]
`parity-util-mem` is no longer maintained.

It was never meant to be a general-purpose crate and only was used in substrate ecosystem, which no longer depends on it.  I can make a patch release (some time next week) which warns users about its usage in README and marks it as unmaintained. 

There are probably some alternatives like https://github.com/bholley/malloc_size_of_derive.

**Comment by pinkforest** [comment]
Cool thanks no worries - we'll just nudge anyone using not to use it
