### ISSUE TITLE
`badge` is unmaintained

### ISSUE THREAD

**Issue by vbrandl** [rustsec/advisory-db#1401]
The [`badge`](https://crates.io/crates/badge) crate is unmaintained and will not receive further updates, as the [code has been removed from the repository](https://github.com/rust-lang/docs.rs/commit/94f3bba6815412bc4672621c4690a93e656486c7).

It is no longer used by the authors and therefore will not receive any updates: https://github.com/rust-lang/docs.rs/issues/1813#issuecomment-1232875809

**Comment by pinkforest** [comment]
How did this get used beyond docs.rs usage ?

Seems only dependant project is cargo-travis by @roblabla

Seems clear maintainer intent in this case .. what would we recommend as an alternative(s) e.g. as actionable fix(es) if we were to flag unmaintained ? 

I think I saw you forked this so you might pick it up a fork too ? Are there other possible alternatives ?

See an example for `informational = "unmaintained"` PR:
https://github.com/rustsec/advisory-db/pull/1400/files

**Comment by vbrandl** [comment]
I maintain a binary project, that is not published on crates.io, that uses the `badge` crate: https://github.com/vbrandl/hoc/blob/master/Cargo.toml#L18

And yes, I'm trying to fork, replace usages the also unmaintained `rusttype` crate.

It's not sure yet, if I can take ownership over the `badge` crate or if the fork will be published using another name.

**Comment by pinkforest** [comment]
Feel free to send a PR when there is either a a fork or a takeover - as an actionable fix

Recent examples:
- wee_alloc - https://github.com/rustsec/advisory-db/pull/1400/files
- mapr - https://github.com/rustsec/advisory-db/pull/1382/files
- dotenv - https://github.com/rustsec/advisory-db/pull/1359/files
