### ISSUE TITLE
`num-format` Status

### ISSUE THREAD

**Issue by pinkforest** [rustsec/advisory-db#1405]
_3,232,716 downloads, ~8k a day_

Last release was over three years ago

It is using the old version of itoa: https://github.com/rustsec/advisory-db/issues/1404

Ralf was helpful to ping earlier: https://github.com/bcmyers/num-format/issues/29

Maintenance status was asked on 9 Jan 2022
https://github.com/bcmyers/num-format/issues/27

@bcmyers - I wonder if people should be still using this crate today and whether it would be helpful to bump the itoa dependency

**Comment by LovecraftianHorror** [comment]
It looks like the maintainer just published a new version

https://github.com/bcmyers/num-format/issues/27#issuecomment-1272626722

**Comment by pinkforest** [comment]
Thanks - great stuff
