### ISSUE TITLE
murmur3 looks abandoned

### ISSUE THREAD

**Issue by rbtcollins** [rustsec/advisory-db#1423]
https://github.com/stusmall/murmur3/issues/18 is my ping for the maintainer; bugs-with-PRs ignored for ~2 years at this point.

**Comment by stusmall** [comment]
I am still maintaining it.  It is a small crate that doesn't need a lot of updates on it.  I've got two open PRs, one of them is feature related.  I'll dig into the correctness one, but when I first looked at it I didn't see the correctness issue claimed.

**Comment by pinkforest** [comment]
Oh sweet - thanks for the clarification :)

**Comment by rbtcollins** [comment]
@stusmall the correctness issue is discussed in the bug - https://github.com/stusmall/murmur3/issues/15 - but thank you for taking the time to look at the PR.
