### ISSUE TITLE
`rmp-serde` Unsound

### ISSUE THREAD

**Issue by pinkforest** [rustsec/advisory-db#1426]
https://github.com/3Hren/msgpack-rust/issues/305
https://gist.github.com/Lucretiel/5deaf285f06a85056aa76276abf9bd77

@Lucretiel would you mind contributing a PR on `informational = "unsound"` advisory on this ?

Do we know what release these Raw deprecations ended up into ?

**Comment by Lucretiel** [comment]
They were deprecated (but not yet removed) in 1.1.0

**Comment by Lucretiel** [comment]
Sure, I can start a report; is there a guide for how to write them?

**Comment by pinkforest** [comment]
@kornelski just wondering re: release for rmp-serde w/ removed Raw ? We can also mention the deprecation. Thanks

**Comment by pinkforest** [comment]
@Lucretiel That would be lovely ! 

You can send a pull request, create crates/rmp-serde/RUSTSEC-0000-0000.md

For an example for unsound:
https://github.com/rustsec/advisory-db/pull/1389/files

For the date use when you reported the issue originally - it's backdated

Cheers

**Comment by Lucretiel** [comment]
It appears that `Raw` itself wasn't deprecated, but `from_utf8` was. There's still potential unsoundness in the serialize -> deserialize path. I haven't seen any justification for why type exists in the first place so it remains my position that it should be deprecated and removed entirely.

**Comment by pinkforest** [comment]
Cool - yeah if we could please document all those different vectors despite them being deprecated so the user will have informed choice on which APIs to use. Cheers

**Comment by kornelski** [comment]
Fixed in rmp-serde 1.1.1
