### ISSUE TITLE
RUSTSEC-2020-0053 isn't valid any more

### ISSUE THREAD

**Issue by michalfita** [rustsec/advisory-db#1427]
The advisory recommends replacement of [`dirs`](https://github.com/soc/dirs-rs) which looks as actively maintained looking at GitHub history with [`dirs-next`](https://github.com/xdg-rs/dirs) crate that hasn't been updated for 2 years now.

Utter nonsense. Please invalidate that entry.

Thank you.

**Comment by tarcieri** [comment]
`RUSTSEC-2020-0053` is marked `withdrawn = "2021-04-19"`

We keep it in the repository for historical purposes, however it will not be surfaced to users of tools like `cargo audit`.

**Comment by michalfita** [comment]
🤔 OK, sorry. `cargo deny` throws it at me... bug there?

Thanks.

**Comment by tarcieri** [comment]
What version?
