### ISSUE TITLE
`crc32c` incorrect results on big endian targets

### ISSUE THREAD

**Issue by nissaofthesea** [rustsec/advisory-db#1442]
The `crc32c` crate produces incorrect results on big endian targets (see this issue: https://github.com/zowens/crc32c/issues/34).

**Comment by Shnatsel** [comment]
Thank you for the report!

crc32 is neither a cryptographic hash nor an authentication code. I agree that this is a bug, but I do not see how this is a security issue. Could you elaborate?

**Comment by nissaofthesea** [comment]
Yup, you're absolutely right. Closing this.
