### ISSUE TITLE
surf seems to be unmaintained

### ISSUE THREAD

**Issue by djc** [rustsec/advisory-db#1471]
The surf HTTP client seems to be unmaintained. I [reached out](https://github.com/http-rs/surf/issues/352) and it doesn't look good. It depends on the latest released version of http-types, which depends on an old version of cookie which in turns depends on the unmaintained stdweb, an old version of aes-gcm which in turns has a number of unmaintained dependencies. There's [an issue](https://github.com/http-rs/http-types/issues/505) in http-types to get a new release out but not much movement there.

surf itself additionally still depends on rustls 0.18, while 0.19 was released two years ago.

**Comment by pinkforest** [comment]
Commented here: https://github.com/http-rs/surf/issues/352#issuecomment-1327778764

The maintainer has indicated willingness to merge any security fixes and per our policy we reserve unmaintained for completely unreachable maintainers or where the maintainer explicitly wishes us to flag it.

An action here might be feasible to flag old versions of rustls and then that will light up anything downstream if feasible ?

**Comment by pinkforest** [comment]
Can't do anything here since the maintainer has said they will fix any security issue and we take the maintainer's word.

Also have offered to mark old versions of rustls unmaintained as the dependencies further up can be used to light up things

Please let us know if you would like us to do that and we can do that to ensure any downstream dependencies complain if they use the old rustls version.

**Comment by djc** [comment]
There's an explicit comment from the maintainer that it should be considered unmaintained:

https://github.com/http-rs/surf/issues/352#issuecomment-1709404352

Is that enough to file this?

**Comment by decathorpe** [comment]
It looks like nothing has changed in the last 1.5 years, so I think this makes the case for "this is really unmaintained" even stronger?

**Comment by djc** [comment]
@decathorpe if you submit a PR I will review.
