### ISSUE TITLE
`ckb` GHSAs

### ISSUE THREAD

**Issue by pinkforest** [rustsec/advisory-db#1484]
GHSA-7fw6-6mfj-g3q2: ckb - Transaction header_deps validation issue (network forking)
GHSA-mcmr-49x3-4jqm: ckb - type_id script resume may randomly fail

@doitian Can we re-publish as-is CC-BY0 as GHSA is CC-BY4 ? Cheers - Feel free to send a PR

**Comment by amousset** [comment]
Closing, as we got no answer from the author and we will import them directly from GHSA at some point.
