### ISSUE TITLE
`personnummer` GHSA-28r9-pq4c-wp3c

### ISSUE THREAD

**Issue by pinkforest** [rustsec/advisory-db#1491]
[GHSA-28r9-pq4c-wp3c: personnummer - vulnerable to Improper Input Validation](https://github.com/advisories/GHSA-28r9-pq4c-wp3c).

@Johannestegner do we have the permission to re-publish as-is as CC-BY0 since GHSA is CC-BY4 ? Thanks

**Comment by Johannestegner** [comment]
All good from our side!

Thank you for asking :)
