### ISSUE TITLE
Advisory against some Hyper versions?

### ISSUE THREAD

**Issue by frewsxcv** [RustSec/advisory-db#15]
All versions of Hyper prior to 0.9.4 [do not do hostname validation](https://github.com/hyperium/hyper/commit/01160abd92956e5f995cc45790df7a2b86c8989f) and [used insecure cyphers and had compression enabled](https://github.com/hyperium/hyper/commit/54bf6adeee1c3a231925f3efa7e38f875bc2d4d5).

https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v094-2016-05-09

Version 0.9.5 disabled hostname validation on Windows because it wasn't working.

Though as of version 0.10.0, rust-openssl was ripped out and now the user is responsible for choosing a TLS library.

**Comment by tarcieri** [comment]
Yep, thanks for reporting. I've been meaning to file an advisory for this, along with rust-openssl itself /cc @sfackler

**Comment by sfackler** [comment]
That seems reasonable to me.

**Comment by tarcieri** [comment]
Advisory PRs opened as #18 and #19.
