### ISSUE TITLE
Tokio: reject_remote_clients configuration may get dropped when creating a Windows named pipe 

### ISSUE THREAD

**Issue by carllerche** [rustsec/advisory-db#1506]
[Github security advisory](https://github.com/tokio-rs/tokio/security/advisories/GHSA-7rrj-xr53-82p7)

**Comment by Shnatsel** [comment]
Thank you. Can you also confirm, as the author of the advisory, that you're OK with releasing the information into the public domain?

GHSA has a more restrictive license that's not compatible with ours (although we're looking into changing that).

**Comment by carllerche** [comment]
Ah yes, release in public domain is fine.
