### ISSUE TITLE
`rustc-hex` seems to be unmaintained

### ISSUE THREAD

**Issue by Nugine** [rustsec/advisory-db#1514]
Last change is in 2020. The author is not responding.
+ https://github.com/debris/rustc-hex/issues/6

**Comment by pinkforest** [comment]
Thanks for the contribution -

We do reserve unmaintained for crates where the owner is completely unreachable for 90 days -

However this has no dependencies and I don't either see anything that needs updating nor any issues or pull requests ?

Re-open if there is anything that requires updating in this crate which I may have neglected ?
