### ISSUE TITLE
Create advisory for Rust miscomilation bug which affects aes-soft

### ISSUE THREAD

**Issue by newpavlov** [rustsec/advisory-db#152]
See: rust-lang/rust#63791

**Comment by richardwhiuk** [comment]
Similarly, should there be an advisory for:

- Rust 1.45.0: https://github.com/rust-lang/rust/issues/74739

- Rust 1.41.0: https://blog.rust-lang.org/2020/02/27/Rust-1.41.1.html

In theory, these could cause security vulnerabilities?

**Comment by pinkforest** [comment]
For some reason aes-soft never got never got an advisory - or it's not there atm
https://github.com/RustCrypto/block-ciphers/issues/51#issuecomment-524587434

I started a wider discussion whether we should file advisories against Rustc - which we don't atm
https://github.com/rustsec/advisory-db/discussions/1353

We need to see if it is feasible to file advisories against Rustc first - Closing until that is resolved.
