### ISSUE TITLE
`warp` missing advisory

### ISSUE THREAD

**Issue by adumbidiot** [rustsec/advisory-db#1524]
I just realized that warp is missing an advisory for the issue similar to https://github.com/rustsec/advisory-db/pull/1159. The tracking issue for this bug was https://github.com/seanmonstar/warp/issues/937, and it was fixed by https://github.com/seanmonstar/warp/pull/997, which was released as 0.3.3. I think it is important to carry an advisory as it appears that the fix was not backported to the 0.2.x or 0.1.x branches. The maintainer was asked to file an advisory in https://github.com/seanmonstar/warp/issues/937, but it looks like they forgot to after fixing the issue. What are the next steps to be taken?

**Comment by pinkforest** [comment]
Would you like to send a PR ? Woule be very welcome - thanks !

**Comment by adumbidiot** [comment]
Sorry for the late response, I'll file one now.
