### ISSUE TITLE
`tokio` soundess fix

### ISSUE THREAD

**Issue by carllerche** [rustsec/advisory-db#1532]
See https://github.com/tokio-rs/tokio/issues/5372

We deemed it did not reach the threshold of CVE. The issue is fixed on our latest stable version (1.24.2) and our two LTS branches (1.20.4, 1.18.5).

If this is something rustsec tracks, feel free to add an advisory.

**Comment by Shnatsel** [comment]
Thanks for the heads-up! This is something we might track as an informational advisory, surfaced only as a warning in our tools.
