### ISSUE TITLE
Patched bug in bzip2 0.4.3

### ISSUE THREAD

**Issue by Plecra** [rustsec/advisory-db#1546]
https://github.com/alexcrichton/bzip2-rs/pull/86
https://github.com/advisories/GHSA-96jv-r488-c2rj

With specific payloads, it was possible to avoid the bounds checks in `bzip2` and get it stuck working forever. The PR linked fixed this issue and was published as 0.4.4

**Comment by pinkforest** [comment]
Hey thanks a lot - I wrote a PR #1554 to get the CVE in
