### ISSUE TITLE
error: couldn't fetch advisory database: git operation failed: no signature on commit

### ISSUE THREAD

**Issue by emk** [RustSec/advisory-db#155]
Hello, thank you for maintaining `cargo audit`, it's a great idea!

I noticed this error appeared about 10 minutes ago.

**Comment by tarcieri** [comment]
Should've been fixed by #156. Can you confirm?

I'm wondering if the signature check is an unhelpful misfeature.

**Comment by emk** [comment]
It's fixed! Thank you very much.

I think the signature check is a nice idea, and it probably makes security auditors happy. On the other hand, some people call `cargo audit` when building binaries releases on their CI system, so missing signatures could break builds.

In any case, thank you for maintaining the database!
