### ISSUE TITLE
buf_redux might be unmaintained

### ISSUE THREAD

**Issue by oherrala** [rustsec/advisory-db#1602]
Ping the repository owner and maintained @abonander. No reaction to any open pull request or issues since 2019 in the repository. Last crates.io release also from 2019.

My question about maintenance status has been unanswered so far https://github.com/abonander/buf_redux/issues/22

And there's also future incompatibility warning https://github.com/abonander/buf_redux/issues/23.

**Comment by Ltrlg** [comment]
According to GitHub, @abonander archived the `buf_redux` repository yesterday, as well as others:

  - [`multipart`](https://github.com/abonander/multipart): 55 dependents according to crates.io
  - [`multipart-async`](https://github.com/abonander/multipart-async): No dependents according to crates.io
  - [`const-cstr`](https://github.com/abonander/const-cstr): Not the one on crates.io
  - [`safemem`](https://github.com/abonander/safemem): 12 dependents according to crates.io, including `multipart`.

At least `multipart` should probably get an unmaintained notice too.

**Comment by oherrala** [comment]
I created unmaintained advisory PRs for 
 * const-cstr: https://github.com/rustsec/advisory-db/pull/1613
 * safemem: https://github.com/rustsec/advisory-db/pull/1615
 * buf_redux: https://github.com/rustsec/advisory-db/pull/1614

**Comment by dignifiedquire** [comment]
Created a fork of `buf_redux` which fixed the issues: https://crates.io/crates/buffer-redux, which should be fully API compatible.
