### ISSUE TITLE
mach might be unmaintained

### ISSUE THREAD

**Issue by oherrala** [rustsec/advisory-db#1604]
Ping the repository owner and maintainer @fitzgen and @gnzlbg who has some of the latest commits.

Last crates.io release in 2019. No new commits in the repository since 2019, and issues and pull requests without reaction since 2019.

A issue from 2020 asked about maintenance of this crate https://github.com/fitzgen/mach/issues/63 which is still unanswered.

There seems to be more active fork `mach2` (https://github.com/JohnTitor/mach2) of this crate.

**Comment by thomcc** [comment]
See https://github.com/JohnTitor/mach2/issues/13
