### ISSUE TITLE
`tui` may be unmaintained

### ISSUE THREAD

**Issue by parasyte** [rustsec/advisory-db#1610]
See https://github.com/fdehau/tui-rs/issues/654#issuecomment-1423118467 from the maintainer @fdehau.

It looks like they wish to transfer ownership to the community. But due to life stuff, they have not been able to put their plan into action. In the meantime, the community has decided to fork the repo and plans to publish it under a different name "ASAP": https://github.com/tui-rs-revival/tui-rs-revival/discussions/63

> As we were not able to get the repository transferred, we will have to upload the first version as new crate.

**Comment by tarcieri** [comment]
Confirm that `tui` (mostly) appears to be explicitly unmaintained, with an author's statement that they want to transfer maintenance of the project to others, and also confirm that `ratatui` appears to be the established successor.

I'm going to go ahead and link this issue on https://github.com/fdehau/tui-rs/issues/654 asking for confirmation.

**Comment by ZeWaka** [comment]
This has been confirmed, per their update to the README:
![image](https://github.com/rustsec/advisory-db/assets/4741640/4b935d58-ead1-435a-9d04-2c38f5d39f69)

**Comment by tarcieri** [comment]
Sounds like we can consider `tui` unmaintained if anyone would like to file an advisory

**Comment by orhun** [comment]
I will be filing an advisory shortly.
