### ISSUE TITLE
Link to HOWTO_UNMAINTAINED.md in README.md?

### ISSUE THREAD

**Issue by smoelius** [rustsec/advisory-db#1748]
Would you consider a PR that adds the following line just above the big red button in README.md?
> See [HOWTO_UNMAINTAINED.md] before filing an advisory for an unmaintained crate.

From what I can tell, HOWTO_UNMAINTAINED.md is currently referenced only from MAINTAINERS_GUIDE.md, which most users are unlikely to read.

Linking HOWTO_UNMAINTAINED.md directly from README.md would make it easier to find.

EDIT: Thank you for providing this valuable service to the community, BTW.

[HOWTO_UNMAINTAINED.md]: https://github.com/RustSec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

**Comment by tarcieri** [comment]
Sure, sounds good
