### ISSUE TITLE
`rust-bus` crates are possibly unmaintained

### ISSUE THREAD

**Issue by simonsan** [rustsec/advisory-db#1756]
I just discovered https://github.com/rust-bus to be unmaintained and archived. They have a lot (possibly 118) of (now unmaintained?) crates on crates.io: https://crates.io/teams/github:rust-bus:maintainers

Does this need a ~~security~~ unmaintained crates advisory?

I couldn't extract information regarding this special case from https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md

54 crates they maintained on crates.io are updated within the last year.
The other 64 crates have been updated the last time over more than a year ago. Which makes me think, that `rust-bus` maintainers could be one of the main maintainers of these crates, and it might be warranted to assume they are now unmaintained?

**Comment by amousset** [comment]
I don't think this calls for a general action for all impacted crates (which also matches the [approach adopted](https://github.com/rust-lang/crates.io/issues/7013#issuecomment-1695190775) by the crates.io team). Most of these crates should have other maintainers, and in this case our usual maintenance policy applies.

However, crates having only `rust-bus` as maintainer on crates.io are probably worth an "unmaintained" advisory.

**Comment by kornelski** [comment]
Rust-bus was used a backup. The org didn't actively intervene, so the de-facto maintenance status of these crates hasn't changed.
