### ISSUE TITLE
`lexical` is a popular crate with a lot of UB

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#1757]
https://github.com/Alexhuszagh/rust-lexical/issues lists a large amount of soundness issues, and the crate has not been updated in over a year. It has 15,000 daily downloads. We should file an advisory for it.

**Comment by Nugine** [comment]
Is there any alternative?

**Comment by Shnatsel** [comment]
For floats: https://crates.io/crates/fast-float

For integers:
https://crates.io/crates/atoi
https://crates.io/crates/btoi

There's also [atoi_simd](https://crates.io/crates/atoi_simd) but I've tried fuzzing it and the fuzzer has discovered straight-up buffer overreads in under a minute, so it's even more broken than `lexical`. I'll file issues upstream about it shortly.

**Comment by Shnatsel** [comment]
And there's also https://crates.io/crates/minimal-lexical but that also needs to be carefully checked for soundness

**Comment by saethlin** [comment]
fast-float is also not in the best shape, it has a soundness issue. A fix was merged 2 years ago and never released.
https://github.com/aldanor/fast-float-rust/issues/28

But I'm pretty sure I've seen the author around, so they can probably be encouraged to cut a new release.

**Comment by dtolnay** [comment]
Not necessarily broadly applicable as an alternative, but `serde_json` contains a vendored fork of `minimal-lexical` from which I stripped the unsafe code. Someone should feel free to extract this to a new crate if it's an easier starting point than current `minimal-lexical`. https://github.com/serde-rs/json/tree/v1.0.105/src/lexical
