### ISSUE TITLE
Memory explosion issue in rustix

### ISSUE THREAD

**Issue by djc** [rustsec/advisory-db#1808]
https://github.com/advisories/GHSA-c827-hfw6-qwvm

Should we set up some GHSA -> RustSec syncing? After RUSTSEC-2023-0065 it seems like projects are increasingly filing GHSAs without also filing a RustSec advisory.

**Comment by tarcieri** [comment]
@djc it's bee under development for quite some time: https://github.com/rustsec/rustsec/pull/656

See also: #644

**Comment by sunfishcode** [comment]
In rustix's case, the bug doesn't seem to meet [the criteria](https://github.com/RustSec/advisory-db/blob/main/CONTRIBUTING.md#criteria). It's a memory-usage explosion DoS, and the code is not advertised as panic-free. Beyond that, it's in an uncommonly used function, it requires the calling code to ignore errors, and it requires uncommon external circumstances to hit the bug. That said, if people here think a RUSTSEC advisory is worthwhile, I'd be happy to file one.

**Comment by tarcieri** [comment]
Indeed, that sounds like it would *not* meet our criteria.

**Comment by djc** [comment]
If you thought it was worth a GHSA IMO it would be better if we also have a RustSec advisory such that tooling like cargo-deny and Dependabot can agree.

Also honestly not sure I agree with this criterion:

> Panics in code advertised as "panic-free" (particularly if useful for network DoS attacks)

Maybe it would be better to invert to something like "Panics from APIs where the panicking conditions are not clearly documented (particularly if useful for network DoS attacks)" -- that is, kind of reversing the burden of proof.

**Comment by Shnatsel** [comment]
A pull request has been opened for this issue: https://github.com/rustsec/advisory-db/pull/1812

**Comment by sunfishcode** [comment]
@Shnatsel Would you mind commenting on why you opened that PR? Do you disagree with my interpretation of the criteria here, or do you disagree with the criteria?

**Comment by Shnatsel** [comment]
I didn't open that PR :sweat_smile:

**Comment by sunfishcode** [comment]
Oops, sorry, it appears I got the wrong name there.

@alexanderkjall Would you mind commenting on why you opened that PR?

**Comment by alexanderkjall** [comment]
@sunfishcode I have some of my projects on github, and some on other forges that doesn't have dependabot, and noticed that dependabot created a PR to fix this in one of my github projects and simply thought this was a case of some missing data-entry work for it to also affect my other projects.

Feel free to close it if it doesn't meet the criteria, I wasn't aware of this discussion when I opened it.

**Comment by djc** [comment]
Opened #1813 to discuss whether RustSec policy should change to increase alignment with GHSA.
