### ISSUE TITLE
`generational-arena` appears unmaintained

### ISSUE THREAD

**Issue by nathaniel-daniel** [rustsec/advisory-db#1883]
Hello, I wasn't use if this abides by the unmaintained guidelines, so I thought I'd ask.

The [generational-arena](https://github.com/fitzgen/generational-arena) crate has been archived. Does this this qualify as being explicitly marked as unmaintained?

Additionally, there appears to have been an [issue](https://github.com/fitzgen/generational-arena/issues/55) on the tracker questioning maintenance status that went unanswered.

Would it be acceptable to file an unmaintained advisory for this crate?

**Comment by Shnatsel** [comment]
Yes, crates explicitly archived by the maintainer clearly warrant a notice that the crate is unmaintained.
