### ISSUE TITLE
Constant-time verification in Argon2 crates

### ISSUE THREAD

**Issue by djc** [RustSec/advisory-db#189]
I found that both rust-argon2 and argonautica do not attempt to implement constant-time comparison for the verification of passwords. Not sure how important that is in this context, but given that the reference implementation does implement it, it seems like a risk.

https://github.com/sru-systems/rust-argon2/issues/21
https://github.com/bcmyers/argonautica/issues/19

**Comment by djc** [comment]
argon2rs does implement constant-time verification:

https://github.com/bryant/argon2rs/blob/master/src/verifier.rs#L388

just-argon2 defers to the reference implementation.

**Comment by tarcieri** [comment]
While I'd consider it a best practice, and [there are some clever attacks (on e.g. unsalted passwords)](https://security-assessment.com/files/documents/presentations/TimingAttackPresentation2012.pdf), generally an attacker can't gain advantage from a non-constant-time comparison of a password hash, so personally I don't think it's worth opening an advisory for.
