### ISSUE TITLE
opentelemetry_api is removed from the github project

### ISSUE THREAD

**Issue by jayvdb** [rustsec/advisory-db#1994]
https://crates.io/crates/opentelemetry_api doesnt mention that it is deprecated.

It was removed from their repo in https://github.com/open-telemetry/opentelemetry-rust/pull/1226 , merged August 2023

As a result, it is now unmaintained.

**Comment by hdost** [comment]
> 
> As a result, it is now unmaintained.
> 
> 

It was migrated from `opentelemtry_api` to `opentelemetry` the transition should be a migration a simple Search and Replace (depending on which version you upgrade to)
