### ISSUE TITLE
RustSec.org is down

### ISSUE THREAD

**Issue by uilianries** [RustSec/advisory-db#206]
Hi! I can't access the address https://rustsec.org

I thought it was only me, but according isitdownrightnow, the website is down for everyone.

https://www.isitdownrightnow.com/rustsec.org.html

**Comment by tarcieri** [comment]
It's a DNS issue that should resolve soon

**Comment by uilianries** [comment]
Thanks for your quick answer!

**Comment by nothingismagick** [comment]
![Screen Shot 2019-12-11 at 14 59 10](https://user-images.githubusercontent.com/35242872/70627621-d9679280-1c26-11ea-8977-d41feb6926c3.png)

**Comment by tarcieri** [comment]
GitHub Pages is issuing a new X.509 certificate. Give it ~24H.

**Comment by tarcieri** [comment]
The cert should be updated now

**Comment by nothingismagick** [comment]
Confirmed.

**Comment by tarcieri** [comment]
Cool, closing this issue then. Apologies for the brief outage.
