### ISSUE TITLE
Add unaffected metadata to RUSTSEC-2024-0376?

### ISSUE THREAD

**Issue by eric-seppanen** [rustsec/advisory-db#2093]
RUSTSEC-2024-0376 says that it affects `tonic` < 0.12.3, but that appears to be inaccurate. The bug was introduced in 0.12.2. Earlier versions should be unaffected.

**Comment by LucioFranco** [comment]
@eric-seppanen thanks for calling this out, I posted an updated PR for the sec advisory and also updated the tonic advisory.

**Comment by tarcieri** [comment]
Fixed in #2094
