### ISSUE TITLE
Filter to ignore specific advisory IDs

### ISSUE THREAD

**Issue by jpgoldberg** [RustSec/advisory-db#212]
We would like to use `cargo audit --deny-warnings` as part of our continuous integration, but there are occasionally advisories which we would like to( temporarily) give a pass on. (In the current case, that is RUSTSEC-2019-0031).

Having a mechanism by which we could filter out, say,  RUSTSEC-2019-0031 so that cargo audit would return a success would be extremely helpful.

See https://github.com/rust-lang-nursery/lazy-static.rs/issues/163 for more on the case that is motiving this feature request.

**Comment by jpgoldberg** [comment]
Oops. The feature I requested already exists through `--ignore`.

Note that that flag does not appear when running `cargo audit --help`. So there still is a documentation problem, but that should be a separate issue.

**Comment by tarcieri** [comment]
You're not seeing it in the help? I see it on my side:

<img width="695" alt="Screen Shot 2019-12-30 at 8 10 41 PM" src="https://user-images.githubusercontent.com/797/71606643-a8e98900-2b40-11ea-9d60-ffe8842f8260.png">

Note that it can also be configured in `~/.cargo/audit.toml`. Here's an example:

https://github.com/RustSec/cargo-audit/blob/master/audit.toml.example#L6

**Comment by jpgoldberg** [comment]
It seems I was running an old version of cargo-audit on my laptop.
