### ISSUE TITLE
How can I opt out of "unmaintained" Github issues being created for my project?

### ISSUE THREAD

**Issue by hrxi** [rustsec/advisory-db#2138]
I'm not entirely sure how these issues get created, is that via some Github action on my side or from this repository?

These notifications seem spammy to me and might hide actual security problems. Crates with no problems obvious to me get marked as "unmaintained" and generate an issue on my Github repository.

**Comment by tarcieri** [comment]
It can be disabled in audit.toml: https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example#L11
