### ISSUE TITLE
rust-phf is unmaintained

### ISSUE THREAD

**Issue by GnomedDev** [rustsec/advisory-db#2180]
https://github.com/rust-phf/rust-phf/issues/318 has been open for 3 months now with no response. I'll prepare an advisory PR in the new year, but if someone wants to jump in before me feel free.

**Comment by mati865** [comment]
Looks like it's in maintenance mode. Lack of new feature development doesn't mean a crate is unmaintained.

**Comment by tarcieri** [comment]
Per maintainer reply it’s maintained. Closing.
