### ISSUE TITLE
What's an alt_serde_derive?

### ISSUE THREAD

**Issue by ibaryshnikov** [rustsec/advisory-db#233]
I've just noticed there's
https://crates.io/crates/alt_serde_derive
which points to the same repo as
https://crates.io/crates/serde_derive
It pops up in autocomplete
![serde_alt](https://user-images.githubusercontent.com/9951788/73463022-ad969c80-438d-11ea-9091-eb1fb3f03642.png)
Any information about this package? Is it secure?

**Comment by tarcieri** [comment]
Seems there are a few of these `alt*` crates:

https://crates.io/users/cbeck88

e.g.

- `alt_semver`
- `alt_serde`
- `alt_serde_json`

**Comment by alex** [comment]
They're documented as:

> alt-serde-derive is a copy of serde-derive, which exists to work around cargo feature unification issue 4866

**Comment by pinkforest** [comment]
I think we have nothing to action here so closing this old issue :) Re-open if there was anything we need to raise advisory about.
