### ISSUE TITLE
spinning_top as an alternative to RUSTSEC-2019-0031?

### ISSUE THREAD

**Issue by gendx** [rustsec/advisory-db#234]
After discussing the alternatives to `spin-rs` in https://github.com/phil-opp/linked-list-allocator/issues/22, it turned out that neither of the proposed alternatives (`lock_api` and `conquer-once`) were fitting for this use case. This led to the new https://github.com/rust-osdev/spinning_top crate (instantiating `lock_api`'s API).

As far as I can tell, it's still quite new (version `0.1.0` from 2 days ago), but based on previous code and much more lightweight than other alternatives (therefore easier to integrate in `no_std` contexts for example).

Would it be relevant to add this alternative as well in the advisory?

**Comment by tarcieri** [comment]
Sure! Please open a PR adding it.

**Comment by saethlin** [comment]
`spin` is maintained once again, and the mentioned advisory in this issue title is withdrawn. Can we close this issue?
