### ISSUE TITLE
Add a "last maintained" or "heartbeat" field to advisories database

### ISSUE THREAD

**Issue by tecywiz121** [RustSec/advisory-db#27]
While it seems this project is well maintained, I'd feel a lot more comfortable if the `cargo audit` command could emit a warning if the advisory database stops being updated.

I propose adding a `last-maintained` or `heartbeat` field (pending a better name) to the database containing the last date someone from RustSec looked at the file.

Then `cargo audit` could emit a warning/failure if the database goes some amount of time without being maintained.

**Comment by tarcieri** [comment]
This PR switches to using git to fetch the advisory database, and will return an error if the git repo hasn't been updated in 90 days. I think it should address the spirit of this idea:

https://github.com/RustSec/rustsec-client/pull/20
