### ISSUE TITLE
Include a PGP signature alongside the Advisories.toml file

### ISSUE THREAD

**Issue by tecywiz121** [RustSec/advisory-db#28]
I noticed that you're signing commits with your PGP key, but unless I missed something, I don't think the client actually verifies the signatures.

Since this is a security related repository, I don't think it would be a bad idea to include a PGP signature alongside the `Advisories.toml` file. Maybe a detached ascii-armored file to preserve backwards compatibility.

**Comment by tarcieri** [comment]
Actually GitHub is signing commits with a PGP key, which you get for free when you add a merge commit for each PR.

Regarding `Advisories.toml`: I'd actually like to get rid of it. In fact it is presently out-of-sync with the advisories in the repo (one is missing). Originally I thought it'd be nice to have the database in a single file after having trouble consuming a Git-based advisory repo in RubySec, but maintaining a separate file is a pain, and Cargo already deals with git repos as a necessity via its index.

**Comment by tecywiz121** [comment]
Does cargo verify the commit signatures? If so, that's probably sufficient for me.

**Comment by tecywiz121** [comment]
> Regarding `Advisories.toml`: I'd actually like to get rid of it. [..]

There's definitely some appeal about a single file to download: it's easy to sign with PGP and dead simple to consume.

If it were up to me, I'd keep a single file, and add a `build.rs` script and a travis build to verify that it's up-to-date for now.

**Comment by kpcyrd** [comment]
> Does cargo verify the commit signatures? If so, that's probably sufficient for me.

Not automatically, you need to execute:

    git verify-commit master

**Comment by tarcieri** [comment]
> Does cargo verify the commit signatures?

`cargo-audit` would need to verify the signatures. It does not at present, but that'd be relatively easy to add.

**Comment by Shnatsel** [comment]
I'm not sure what the threat model here is. Could you describe an attack that is prevented by the presence of the signature?

**Comment by tecywiz121** [comment]
> I'm not sure what the threat model here is. Could you describe an attack that is prevented by the presence of the signature on Advisories.toml?

The threat is someone gaining access to the GitHub or a MITM attack on the download.

**Comment by tarcieri** [comment]
@Shnatsel I would generally agree with that.

**Comment by tecywiz121** [comment]
Another nice benefit of PGP signatures is that they can be mirrored without trusting the mirror itself. Hypothetically a large company could start using `cargo audit`, and could mirror/cache the database to speed up their builds.

In any case, I definitely wasn't suggesting this as a super high priority issue, just a "would be nice". The chance of someone breaking into a GitHub account, or a GitHub employee maliciously modifying the repository is tinfoil hat levels of paranoia.

**Comment by tarcieri** [comment]
I think verifying the signatures which GitHub is already adding to the repository is a relatively low effort solution to this problem... but the prerequisite work would be switching from an `Advisories.toml`-based distribution model for the vulnerability database to one which fetches the entire repository.

I've opened an issue about that here:

https://github.com/RustSec/advisory-db/issues/29

**Comment by tecywiz121** [comment]
I don't have any objections to verifying the commit signatures instead of a detached PGP signature, so I'm closing.

**Comment by tarcieri** [comment]
As of https://github.com/RustSec/rustsec-client/pull/20 the `rustsec` crate now fetches the git2 repository.

The signature is annoyingly RSA, which can be verified by `ring` or OpenSSL. I'd personally prefer the former.

**Comment by tarcieri** [comment]
rustsec 0.7 is out and extracts the signatures from git. I opened an issue about potentially verifying them:

https://github.com/RustSec/rustsec-client/issues/33
