### ISSUE TITLE
`dirs` and `directories` crates unmaintained?

### ISSUE THREAD

**Issue by tarcieri** [RustSec/advisory-db#282]
Saw this here:

https://www.reddit.com/r/rust/comments/ga7f56/why_dirs_and_directories_repositories_have_been/

The `dirs` and `directories` (EDIT: and `dirs-sys`) crates have been archived on GitHub. ~~No one has been able to figure out why or heard back from the author~~ (edit: someone claims to have received an email from the author and the [situation seems bad](https://www.reddit.com/r/rust/comments/ga7f56/why_dirs_and_directories_repositories_have_been/foyqipp/))

Some stats on current usage:

- [`dirs`](https://github.com/soc/dirs-rs)
  - downloads: ~15,000/day
  - dependent crates: 523
- [`directories`](https://github.com/soc/directories-rs)
  - downloads: ~4,000/day
  - dependent crates: 116
- [`dirs-sys`](https://github.com/soc/dirs-sys-rs)
  - downloads: ~13,000/day
  - dependent crates: 3

I don't want to be too hasty in filing advisories as that seems rather disruptive and we should probably wait and see what's going on first and if there's some sort of handoff to new owners. But if they're really unmaintained, we should document that.

The [`home` crate](https://github.com/brson/home) is an alternative, but does not provide equivalent functionality (e.g. XDG directories, though it seems the [`xdg` crate](https://crates.io/crates/xdg) might fit the bill there)

**Comment by lzutao** [comment]
I created @xdg-rs for maintaining those crates. Please join if you interest.

Currently we only have publishing permission for "dirs". 
I mailed and kindly asked Simon for ownership for other crates. He hasn't responded yet.
In worst case, we will have to publish the same crates under different names.

**Comment by tarcieri** [comment]
Neat! Let us know how it works out.

**Comment by Shnatsel** [comment]
A fork to maintain those crates has just been announced: https://www.reddit.com/r/rust/comments/gli4pc/directoriesnext_dirsnext_the_new_home_for/

**Comment by ArekPiekarz** [comment]
Is dirs still unmaintained? Its repository is no longer read-only and there has been a new release on June 21.

**Comment by tarcieri** [comment]
Looks like we can close this

**Comment by tarcieri** [comment]
Update: we merged #430 that marks them as unmaintained again as the repos have been archived. It seems like `dirs-next` and `directories-next` are the successors.
