### ISSUE TITLE
`failure` has been deprecated

### ISSUE THREAD

**Issue by tarcieri** [RustSec/advisory-db#284]
Discussion here:

https://internals.rust-lang.org/t/failure-crate-maintenance/12087/16?u=bascule

`failure` is a fairly pervasive crate and marking it as unmaintained immediately would be rather noisy.

On the discussion thread above I suggested waiting for some period of time for people to organically migrate to new crates, then filing an advisory.

Perhaps 3 months is enough time? (so August 2020)

**Comment by djc** [comment]
It's the end of August. Let's do it?

Just pointed some colleagues at the deprecation, and they pointed out that it's not very obvious right now.

**Comment by tarcieri** [comment]
Opened #368 which adds an unmaintained advisory with suggested alternatives of `anyhow`, `eyre`, `snafu`, and `thiserror`.

**Comment by tarcieri** [comment]
Filed as `RUSTSEC-2020-0036`.
