### ISSUE TITLE
Add  the 'obsolete' field in the advisories 

### ISSUE THREAD

**Issue by sbs2001** [RustSec/advisory-db#289]
https://github.com/RustSec/advisory-db/blob/aa789b9cbd6a03c860c7a1f508cb60ae9f22e3eb/crates/plutonium/RUSTSEC-2020-0011.toml#L5 has the field `obsolete` , upon grepping the repo, I found this as the only advisory containing this field.

If it is planned to add this field in  the schema , please add that to README , that would be very helpful detail for us at https://github.com/nexB/vulnerablecode as we are essentially consuming this repo. Thanks.

**Comment by tarcieri** [comment]
I've been thinking about renaming this field to `yanked`, as it were...

**Comment by tarcieri** [comment]
You might also check out #240, which is a pretty big (proposed) change to the advisory format

**Comment by sbs2001** [comment]
@tarcieri thank you very much, that is really a valuable information, (our project essentially breaks after these schema changes :P ) 
I see the schema would be freezed after implementing V3 advisory format, that would be really great. Thanks again.

**Comment by Shnatsel** [comment]
This has been implemented, although apparently it remains undocumented (#928). Closing.
