### ISSUE TITLE
Create advisories for Actix

### ISSUE THREAD

**Issue by Shnatsel** [RustSec/advisory-db#294]
It has been pointed out that we currently do not carry any advisories for Actix, even though some versions of it contain unsafe code that is known to be problematic. We should notify people about the issues, starting with the very old, uncontroversially problematic versions. Advisories for more recent versions should probably be coordinated with Actix maintainers.

**Comment by tarcieri** [comment]
Corresponding Actix issue: https://github.com/actix/actix-web/issues/1296

**Comment by Shnatsel** [comment]
Here's one for very old actix from 2018 with tons and tons of unsafe:
https://rustsec.org/advisories/RUSTSEC-2018-0019.html

And these were fixed in the 3.0 release:
https://rustsec.org/advisories/RUSTSEC-2020-0045.html
https://rustsec.org/advisories/RUSTSEC-2020-0046.html
https://rustsec.org/advisories/RUSTSEC-2020-0048.html
https://rustsec.org/advisories/RUSTSEC-2020-0049.html

If I've missed anything, please let me know.
