### ISSUE TITLE
File advisories for vulnerabilities with upcoming fixes

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#327]
I am aware of a number of memory safety issues that are slated to get fixes soon™ but do not have a release shipping yet. My life is a bit of a struggle as of late, so I don't have the capacity to follow up on them properly. I'm dumping them here so that someone else could follow up on them and issue advisories.

- [x] https://github.com/actix/actix-net/issues/160
- [x] https://github.com/actix/actix-net/issues/91
- [x] https://github.com/actix/actix-web/issues/1321
- [x] https://github.com/kornelski/rust-rgb/issues/35
- [ ] https://github.com/ImageOptim/mozjpeg-rust/issues/10

**Comment by expnkx** [comment]
It does not work and it will never work. Unsafe should never be used or unsafe should only be used in exceptional circumstances is the fallacy and exactly the issues of these problems.

Stop telling other people how they should write code. It does not work.

**Comment by pinkforest** [comment]
I drafted the last one for mozjpeg:
https://github.com/rustsec/advisory-db/pull/1389
