### ISSUE TITLE
Web UI for vulnerability database

### ISSUE THREAD

**Issue by tarcieri** [RustSec/advisory-db#34]
There is presently no way to browse the vulnerability database other than by reading the individual TOML files in the repository.

It would be nice to render all of the vulnerabilities such that they have a directly linkable advisory URL. This could be done using e.g. GitHub pages or Firebase such that the content is automatically rebuilt in CI.

Another alternative is to render content for the `advisory-db` Wiki

**Comment by frewsxcv** [comment]
i started work on a small crate for rendering the advisories.toml file in this repo: https://github.com/frewsxcv/advisory-db-renderer/blob/master/src/main.rs . ran out of time this morning, but just needs to be extended to write some html

**Comment by tarcieri** [comment]
As it so happens, I just made a web site as well (as in literally pushed it a few minutes ago), however my markdown renderer is a Ruby script, so having something in Rust to generate the Markdown files would be nice:

https://rustsec.org/

**Comment by tarcieri** [comment]
Note the repo is here:

https://github.com/RustSec/rustsec.github.io

I'm basically "done" as far as it's just all static files, which is manageable for now, but I'd love for someone to automate it cc @frewsxcv 

Also open to ideas about different workflows. It's GitHub pages + Jekyll for now, but could easily be something a bit easier to work into the CI workflow.

**Comment by tarcieri** [comment]
I'll call this issue closed, but a builder for the markdown files would definitely be nice to have
