### ISSUE TITLE
Guidelines for GitHub Advisory Database

### ISSUE THREAD

**Issue by vks** [RustSec/advisory-db#345]
Does it make sense to provide guidelines for the GitHub Advisory Database? It could be mentioned in `CONTRIBUTING.md` as an optional step.

**Comment by tarcieri** [comment]
Sure, what did you have in mind specifically?

One problem is while the `rustsec` crate supports GHSA identifiers as aliases, there's to my knowledge no way to map one of those identifiers to an advisory automatically.

**Comment by vks** [comment]
I was wondering whether we should file a GitHub advisory for `rand_core` (RUSTSEC-2019-0035, which is informal). Then I thought that there could be some guidance here.

**Comment by tarcieri** [comment]
Sure, and once you do, we can add an alias for its GHSA in the RUSTSEC advisory.

**Comment by vks** [comment]
@tarcieri Ok, I opened a draft and added you as a collaborator. It's GHSA-mmc9-pwm7-qj5w (not published yet).

It seems this would be the first crates.io GHSA and that we can ask GitHub to file a CVE for us. (I think this could be mentioned in the RUSTSEC guidelines.) However, for an informational advisory it's maybe not necessary to assign a CVE?

**Comment by tarcieri** [comment]
Up to you about a CVE. I'd recommend against it in this case.

Advisory looks good. I'd suggest opening a PR that modifies `RUSTSEC-2019-0035.toml` to list `GHSA-mmc9-pwm7-qj5w ` as an `alias`.
