### ISSUE TITLE
memmap looks abandonned

### ISSUE THREAD

**Issue by bbigras** [rustsec/advisory-db#359]
Author never replied to https://github.com/danburkert/memmap-rs/issues/90.

Was also mentioned in #173

I have no idea of an alternative. I hope there's one.

**Comment by bbigras** [comment]
Should there be an advisory to tell people the crate is not maintained?

Maybe it could also help to give it some publicity.

**Comment by tarcieri** [comment]
We generally like for these sorts of advisories to steer people towards maintained alternatives if possible, however if none exist I guess that's ok too?

**Comment by IamTheCarl** [comment]
It looks like this fellow has made a fork and is actually maintaining it to some degree. They've accepted some of the pull requests that are still waiting in the original repo.
https://crates.io/crates/mapr

Although the issue tracker doesn't seem to be available on the github page. Did they disable that? Or is that just some odd side effect of a forked repo?

**Comment by Redrield** [comment]
> Although the issue tracker doesn't seem to be available on the github page. Did they disable that? Or is that just some odd side effect of a forked repo?

I can't remember if it's the default behaviour of github to disable the issues page on forks, but either way there's an option in the project settings where the author should be able to re-enable it.

**Comment by tarcieri** [comment]
There's a lot of weird issues with trying to use a fork of an old project as the new central repo for that project. If the original project is abandoned, it's probably best to create a new repo.

That said, we can point to that repo in an advisory, if someone would like to make one.

**Comment by Redrield** [comment]
There's also https://github.com/RazrFalcon/memmap2-rs which seems to have reset the version number, but is also forked from the original. Should I suggest both as alternatives in the advisory?

**Comment by tarcieri** [comment]
Sure, we try to be comprehensive when listing alternatives in unmaintained crate advisories

**Comment by saethlin** [comment]
I think this should have been closed by https://github.com/rustsec/advisory-db/pull/501, right?
