### ISSUE TITLE
Link original PR number in ID-assigning PR

### ISSUE THREAD

**Issue by Qwaz** [rustsec/advisory-db#380]
ID-assigning GitHub action PRs do not contain any information that can be associated with the original PR (#378 and #373 for example) at the moment. Is it possible to include the original issue ID in an ID-assigning PR?

This would help finding the original discussion from RustSec ID number for a bug and vice versa.

**Comment by tarcieri** [comment]
When I was assigning IDs by hand, I'd usually do:

> Original PR: #NNN

**Comment by pinkforest** [comment]
Hmm can't do this really as we cannot guarantee that the merge commit has the PR number that could be accessible.

I've followed up here: https://github.com/rustsec/rustsec/issues/638 - We can continue there if any - Cheers
