### ISSUE TITLE
stdweb is unmaintained/abandoned

### ISSUE THREAD

**Issue by jhpratt** [RustSec/advisory-db#391]
See koute/stdweb#403, which has been open just shy of four months.

**Comment by tarcieri** [comment]
It worked!

**Comment by strohel** [comment]
@tarcieri and for reference: maintained alternative to stdweb mostly is wasm-bindgen + js-sys + web-sys: https://github.com/rustwasm/wasm-bindgen

(per https://www.reddit.com/r/rust/comments/e7trlf/question_whats_the_difference_between_stdweb_and/fa6lslj?utm_source=share&utm_medium=web2x&context=3 and my own observations)

**Comment by RalfJung** [comment]
FWIW this crate also has [open soundness issues](https://github.com/koute/stdweb/issues/411). Not sure if that would change anything about the advisory though.
