### ISSUE TITLE
Vulnerability notifications

### ISSUE THREAD

**Issue by ralpha** [rustsec/advisory-db#413]
I don't know if this is ever suggested but could not find it.

If there some way to get notified about new (or old) vulnerabilities that might be used in any version of application (not only the most recent)?
I use `cargo audit` and `cargo deny` in my CI pipeline, but this only checks for the current version of the crates I use.

But I still have older versions of my application being used. There is no easy way to check if any of these version have problems (that are only recently found).
This way I can yank/deprecate them so they can no longer be used. (I build in mechanisms to deprecate them)

I'm suggesting that there should be some way to get notified if a crate or specific versions of a crate has problems or any of there dependencies. 
- This can be in the form of running `cargo audit` on a collection of `Cargo.lock` files that I keep (from all the versions of my app). (this can be done with a folder filled with lock files and run `cargo audit -f <filename>` on all of them, I think ) 
- Or an online service I can subscribe to for updates about specific crates. So I get all the security warnings from a list of crates.
- Or a mail list where I can specify crates that I want to know about
- Or something...

Because right now, if a problem gets found in a older version of the crate I'll never know I have to yank/deprecate my old versions.
I thinks there should be something like this.

**Comment by tarcieri** [comment]
Check out `auditable`: https://github.com/Shnatsel/rust-audit

It allows you to embed Cargo.lock-like dependency information in binaries.

You can then collect this information from deployed binaries (e.g. using an agent) and audit it, or at least, that's the plan.

**Comment by 8573** [comment]
> * This can be in the form of running `cargo audit` on a collection of `Cargo.lock` files that I keep (from all the versions of my app). (this can be done with a folder filled with lock files and run `cargo audit -f <filename>` on all of them, I think )

This sounds like it should be simple and workable.  Is there something that makes it not work yet?

**Comment by tarcieri** [comment]
`cargo audit` already has a `-f` flag. You can also pass `-f -` to pass a Cargo.lock file via STDIN.

**Comment by Shnatsel** [comment]
Author of `auditable` here. It is fully functional, but perhaps not very easy to use. I was waiting for someone with a real use case to build more usable tooling, so I could design it around what people actually need instead of what I think they need.

It might also be more granular than Cargo.lock - e.g. it won't warn you about bugs in dev-dependencies that don't affect the final binary, or about bugs in `winapi` if you're only using Linux binaries.

I'm happy to help deploy `auditable` in a real-world setting.

**Comment by ralpha** [comment]
First, `cargo audit -f <filename>` seem to work with a small bash script and all the lock-files in the same folder. (just had not tested it yet, though about while writing the previous post)

Then, I talked to @Shnatsel about `auditable` and seems to be something that can be used for this.
As my application is client side I have to build in a mechanism to upload the embedded dependencies to a server that does the checks.

Because deprecation of old software is something that is hard when users never update or things don't want to die (looking at you Adobe Flash). I'll create a (few) crate(s) that tries to solve this (at least for developers that want to use it).
Before I start working on this, I can describe what I want to create so you can already give feedback (as I see some of you also have a security background :) ).

I'll (try) to keep it short:
Client <-> Server (communicate of http(s))

Client: 
- Has embedded list of dependencies using `auditable` and `auditable-build`.
- Has embedded a list of servers it trusts (URLs).
- Has embedded a list of public keys (maybe certificates?) it trusts (for signature verification).
- When application start (or at another point the developer wants) the embedded list is unpacked from binary and sent to the servers (in minimized JSON format), iterating over them if one does not respond (quickly enough).
- The server then does its checks (see below) and returns a JSON token (Should this be a JWT?) (There should be some way of defining the name/version or hash of the executable so tokens can not be reused across different application, maybe hash of dependencies list?). This token is verified, used and checked next time, until it expires (so it speeds up the application and reduces server load). (has to be stored somewhere, any recommendations?).
- The developer of the app can decide what he wants to do when app should or should not be deprecated.
- Token requirements: (I think this should be similar to certificates) `not valid before`, `not valid after`, `application identifier`(hash or something unique about executable, should be embedded in executable or derived from content in it), `server id`, `public key`, `issued at`(date+time), ...

Server:
- Has a private key it can access.
- Has an ID (`server id` from above).
- Has a list of servers it can get the advisory database from (maybe a backup server somewhere). (and a secure way to verify them and connect to them, is the HTTPS/TLS cert good enough for this? This can be spoofed unless certificate pinning is used, and even then...)
- The server keeps a local copy of the advisory db that it updates every X amount of time. (if it can not update its local version it should no longer validate tokens and force client to ask another server)
- When client request comes in, it checks the dependencies using https://crates.io/crates/rustsec. And if all is well signed a token and returns it. I something is wrong it will return a different signed token that will invalidate the application.

What am I missing? Some of these requirements seems to overlap with certificates, but it should trust another set of CA's.
Now that I typed it out it seems like this is a much bigger task then I was thinking. Given that most of the components are already done, so it is just combining them all and making sure it all works correctly, but still.

But this can be a project used across the whole Rust community and we could even have a list of public servers that can be used by all apps, instead of everyone running there own.

Feedback is very welcome.

**Comment by Shnatsel** [comment]
> Has embedded a list of public keys (maybe certificates?) it trusts (for signature verification).

I'd skip that and just rely on TLS with rustls, otherwise you have to come up with your own certificate revocation too.

**Comment by pinkforest** [comment]
Auditable discussion - there is now new repo and branding @ https://github.com/rust-secure-code/cargo-auditable

Quite bit has changed so closing in favor of keeping issue list in advisory-db clean :) Thanks all :purple_heart:
