### ISSUE TITLE
Support multiple URLs in the URL field

### ISSUE THREAD

**Issue by Qwaz** [rustsec/advisory-db#429]
The current advisory format only allows a single entry in the URL field, but sometimes it is useful to include multiple URLs in advisories.

Examples:
* [RUSTSEC-2019-0034](https://rustsec.org/advisories/RUSTSEC-2019-0034.html) was an advisory for two bugs, hyperium/http#354 and hyperium/http#355. I included the links in the description section and left the URL field empty, because it only supports a single entry.
* [RUSTSEC-2019-0035](https://rustsec.org/advisories/RUSTSEC-2019-0035.html) used a [changelog](https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md#050---2019-06-06) URL that lists PRs and issue IDs patched in that version, but it would be better to include precise issue numbers that are related to the issue in the advisory itself. For instance, rust-random/rand#781 mentioned in the changelog is not directly related to the bug.
* [RUSTSEC-2019-0009](https://rustsec.org/advisories/RUSTSEC-2019-0009.html) put servo/rust-smallvec#148 in the URL section, while servo/rust-smallvec#149 is also relevant.

Is it too late to introduce this kind of breaking changes to the advisory format, or can we still do this as part of V3 migration (#414)?

**Comment by tarcieri** [comment]
I would suggest adding a brand new `references` section in addition to the current `url` field.

The `references` section can be a list/array of URLs, but `url` still provides the most definitive information about a vulnerability.

**Comment by Qwaz** [comment]
I like the name `references`. One question though, what would be the recommendation if there are multiple equally definitive URLs (as in RUSTSEC-2019-0009)? Put one of them in `url` and the other in `references`, leave `url` empty and put both of them in `references`, or something else?

**Comment by tarcieri** [comment]
I think it's up to the advisory author to decide. If there's no definitive one, they could all just be `references`.

**Comment by tarcieri** [comment]
It seems `references` is already used for a list of vulnerability IDs, and there's some usage of it in the current advisory DB, unfortunately.

**Comment by BlackHoleFox** [comment]
Its not as fun as references, but maybe “sources”, as in “information sources”?

**Comment by tarcieri** [comment]
@BlackHoleFox I had a similar thought, but `resources`

**Comment by tarcieri** [comment]
Reflecting on this, I'd *really* like to use `references` for this, but that'd be a breaking change.

One possible way to do it:

- Rename the current `references` section to `related`. This is non-breaking.
- Update the database to move all the existing `references` to `related`
- After clients have been updated (this may not even be breaking), start introducing URL `references`

It'd be interesting to experiment and determine if existing clients *could* parse URLs in the `references` field as well

**Comment by Qwaz** [comment]
RUSTSEC-2016-0002, RUSTSEC-2019-0002, and RUSTSEC-2020-0024 seem to be the only advisories that use `references` field at this point of time.

**Comment by tarcieri** [comment]
PR to rename `references` to `related`: https://github.com/RustSec/rustsec-crate/pull/261

The former is still preserved in the linter.

After that we'll need to rename it in the advisories, and then add support for a new URL-based `references` field.

**Comment by pinkforest** [comment]
This works today as:
`references = ["https://foo.com", "https://bar.com"]`

I've added Doc PR https://github.com/rustsec/advisory-db/pull/1354

Closing as Completed
