### ISSUE TITLE
Auto create issue when failure found

### ISSUE THREAD

**Issue by corentinway** [RustSec/advisory-db#432]
Whenever a failure is found in the crates, it should create an issue on the git repository.

**Comment by 8573** [comment]
What do you mean by "a failure" — what kind of failure, found by what project's CI?

**Comment by WaffleLapkin** [comment]
I'm not sure, but I think that @corentinway meant this: "when an advisory is merged to the database, a bot should open an issue in ptoject's git repo saying that the project has security (/etc) problems"

**Comment by tarcieri** [comment]
Typically the `url` field of an advisory will refer to an already open issue on the upstream repository.

We don't generally file security advisories for issues/vulnerabilities which haven't been reported to the upstream project.

**Comment by tarcieri** [comment]
Not sure there's anything actionable here. Please reopen if you disagree.
