### ISSUE TITLE
Suggestion: Add thread safety related category in advisory metadata

### ISSUE THREAD

**Issue by Qwaz** [RustSec/advisory-db#511]
According to README.md, the valid categories for advisories are:
```
# Optional: Categories this advisory falls under. Valid categories are:
# "code-execution", "crypto-failure", "denial-of-service", "file-disclosure"
# "format-injection", "memory-corruption", "memory-exposure", "privilege-escalation"
```

Thread safety is one of the major guarantee of Rust. Thus, having a thread safety related category here would help classify vulnerabilities. As an example, advisories like [RUSTSEC-2020-0072](https://github.com/RustSec/advisory-db/blob/master/crates/futures-intrusive/RUSTSEC-2020-0072.md) could put this new category in its categories field.

Not a very polished thought, but two names I can think of are:
* "thread-safety"
  * Pros: General and straightforward.
  * Cons: Not in accordance with the naming of other categories. It seems that the other categories are named after what happens when the bug is triggered. The name "thread-safety" can't be used in a sentence like "if this bug is triggered, thread-safety will happen."
* "data-race"
  * Pros: In accordance with the naming of other categories.
  * Cons: There might be thread safety issues that are not data race?

**Comment by 8573** [comment]
If matching the other category names is desired, would negating `thread-safety` to `thread-unsafety` work?
