### ISSUE TITLE
Support a qualified path in `affected.functions`

### ISSUE THREAD

**Issue by Qwaz** [rustsec/advisory-db#512]
Continued from: https://github.com/RustSec/advisory-db/pull/320#issuecomment-650970790

Supporting a qualified path in `affected.functions` field would allow to describe the affected functions more precisely, especially when the bug is inside a trait implementation.

**Comment by tarcieri** [comment]
I relaxed the checks for the contents of this field quite a bit in `rustsec` crate v0.22, but this case is still disallowed.

I'm thinking in the next release we can remove pretty much all of the validity checks from this field and move them into the linting process so they're easy to change.

**Comment by pinkforest** [comment]
This works today now with latest rustsec:

RUSTSEC-0000-0000.md
`functions = { "mycrate::MyType::<impl>Clone::clone" = ["< 1.2.0, >= 1.1.0"] }`

$ rustsec-admin lint . --skip-namecheck rustdecimal|grep 0000
      Linted ok: ./crates/mycrate/RUSTSEC-0000-0000.md

From code all I see now in checks is that the initial `mycrate::` matches crate name mycrate

Closing as completed - We can re-open in rustsec/rustsec if further changes etc.
