### ISSUE TITLE
web: advisory names should be escaped

### ISSUE THREAD

**Issue by Qwaz** [RustSec/advisory-db#555]
It seems that rustsec.org does not escape titles for advisories, which causes RUSTSEC-2020-0074 to be incorrectly rendered on browsers.

Title of the advisory: ``Reference counting error in `From<Py<T>>` ``

Rendered on Chrome:
![rustsec screenshot](https://user-images.githubusercontent.com/5073807/101241640-eeee8b80-36c5-11eb-8c4b-5c78008f89cb.png)
![rustsec screenshot](https://user-images.githubusercontent.com/5073807/101241654-1fcec080-36c6-11eb-9ad3-22014ceb856a.png)

**Comment by tarcieri** [comment]
I opened a tracking issue for improving the https://rustsec.org site generator: https://github.com/RustSec/rustsec-admin/issues/114

**Comment by tarcieri** [comment]
After landing https://github.com/RustSec/advisory-db/pull/810 this appears to be fixed:

<img width="1201" alt="Screen Shot 2021-03-06 at 11 58 01 AM" src="https://user-images.githubusercontent.com/797/110219310-4215dd00-7e73-11eb-81f8-b228e826f2ea.png">
