### ISSUE TITLE
web: suggestion: add a link to the original advisory in rustsec.org

### ISSUE THREAD

**Issue by Qwaz** [rustsec/advisory-db#556]
rustsec.org website only shows selected metadata in its page. To check other metadata, one needs to go to advisory-db repository and search for the advisory number.

To simplify this process, would it be possible for each advisory page to have a link to the advisory page on GitHub? Another approach could be adding "raw" button in a page like GitHub that shows the raw metadata.

**Comment by amousset** [comment]
All metadata should have been added in https://github.com/RustSec/rustsec-admin/pull/133, and there now are  links to view history and edit advisory on Github. Do you think a `[raw]` button would still be relevant?

**Comment by pinkforest** [comment]
I think since all the metadata has been added we can close this - 

Re-open in rustsec/rustsec if we need more or the button is still required.
