### ISSUE TITLE
out_reference 0.1.x is unsound, needs advisory

### ISSUE THREAD

**Issue by Kixunil** [rustsec/advisory-db#613]
https://github.com/RustyYato/out-ref/issues/1

There was no change for the past two years however I'm not eager to declare a small crate with a single specific job unmaintained if it works. So I'd suggest waiting a bit if the issue gets reply before claiming so.

**Comment by RustyYato** [comment]
I'll be passively maintaining `out-reference`, but there isn't much to add to this crate. Feel free to send PRs to add new features, and I'll verify and merge them.

**Comment by Shnatsel** [comment]
The unsoundness deserves an advisory.

Passive maintenance status is not usually something we make an advisory for; it's designed for crates with entirely unreachable maintainers.

**Comment by Shnatsel** [comment]
We currently have a lot of advisories to review, so I would appreciate if you could fill out the advisory template and submit it as a PR. 

See https://github.com/RustSec/advisory-db/blob/master/CONTRIBUTING.md

**Comment by RustyYato** [comment]
Btw. I've yanked all previous versions of `out-reference`, so the damage should be minimal, I'll leave the advisory PR to @Kixunil as I don't have time to work on `out-reference` right now.

**Comment by Kixunil** [comment]
My time is also not great but I will try to do it later.

**Comment by pinkforest** [comment]
@Kixunil would you like to try to send us advisory on this still ? I know it's been like a year but :woman_shrugging: ought to ask first

**Comment by Kixunil** [comment]
Oh, forgot about this and also will be busy at least until Monday. If anyone wants to do it go ahead.

**Comment by pinkforest** [comment]
@Kixunil Monday is fine if you got time :) Help would be most appreciated. Thanks

**Comment by Nugine** [comment]
Any progress?
