### ISSUE TITLE
HTML templating escape function error: worthy of an advisory?

### ISSUE THREAD

**Issue by djc** [RustSec/advisory-db#67]
I had this bug report in the form of a PR: https://github.com/djc/askama/pull/138.

Since lack of correct escaping can result in vulnerabilities, I wonder if this should merit an advisory?

**Comment by alex** [comment]
Yes, I think an advisory would be appropriate.

**Comment by djc** [comment]
Should I get a CVE? If yes, is the DWF Google form still a good place given the discussion in https://internals.rust-lang.org/t/content-of-security-announcements/8492?

**Comment by alex** [comment]
CVEs are good. I recommend requesting one from MITRE directly https://cveform.mitre.org/ they're faster than DWF in my experience.

**Comment by niklasf** [comment]
It looks like characters can be skipped, but all important characters are still escaped. Is it possible to use this bug to inject HTML?

**Comment by djc** [comment]
@niklasf I think you're right -- the escaping still works, it is just skipping one (safe) character. I guess I was overreacting a bit. Thanks!
