### ISSUE TITLE
Unclear which keywords are available or one should use

### ISSUE THREAD

**Issue by gnzlbg** [RustSec/advisory-db#69]

**Comment by tarcieri** [comment]
The keywords are intended to be freeform ala `Cargo.toml`, however the advisories could probably also benefit from some "categories" which have a fixed schema, perhaps mapping to the existing labels:

https://github.com/RustSec/advisory-db/labels

**Comment by gnzlbg** [comment]
It would be nice if there was some list of keywords to choose from. I honestly have no idea which keywords to use.
