### ISSUE TITLE
Text of advisory is escaped where not necessary in posted issue

### ISSUE THREAD

**Issue by CAD97** [RustSec/advisory-db#708]
e.g. https://github.com/ClementTsang/bottom/issues/401

Image:

![image](https://user-images.githubusercontent.com/5992217/106028679-db421e80-6091-11eb-9515-a004df33bd2e.png)

**Comment by tarcieri** [comment]
See also #555 

The current rendering pipeline is a bit convoluted: it uses Handlebars to output Markdown which is in turn rendered by Jekyll to produce HTML

A simplified rendering pipeline could avoid the escaping problem but is a somewhat substantial task

**Comment by tarcieri** [comment]
I opened a tracking issue for improving the https://rustsec.org site generator: https://github.com/RustSec/rustsec-admin/issues/114

**Comment by tarcieri** [comment]
After landing #810 this should be fixed

<img width="1209" alt="Screen Shot 2021-03-06 at 11 59 42 AM" src="https://user-images.githubusercontent.com/797/110219354-7e493d80-7e73-11eb-844e-31f9a5c6a279.png">
