### ISSUE TITLE
Guidance around yanking crates?

### ISSUE THREAD

**Issue by tarcieri** [RustSec/advisory-db#74]
I think it makes sense to encourage people to yank all releases of any crate which match any vulnerable versions listed in advisories.

This could range from a heavy-handed lint on published crate versions which requires all impacted versions for a crate be yanked before the advisory can be merged, to a lighter touch "you should probably yank those crates" advice in both [CONTRIBUTING.md](https://github.com/RustSec/advisory-db/blob/master/CONTRIBUTING.md) and as a pull request comment.

What do people think about this?

**Comment by 8573** [comment]
My one concern with a requirement that vulnerable versions be yanked is that it would seem to mean that filling vulnerability advisories would begin to require the cooperation of crate owners.

**Comment by tarcieri** [comment]
@8573 that is a good concern! It's also one we could work around with some sort of exemption list.

I'm kind of torn on that particular issue: it would be nice to allow automated filing of vulnerabilities, but at the same time some curation of the database helps keep it consistent and also catch missing details in advisories.

**Comment by Licenser** [comment]
Quick feedback from someone who just filed an advisory. Having at least a hint in the `CONTRIBUTING.md` would have helped me. I wasn't aware I even could yank a crate (I assumed an immutable registry), and while that's clearly my fault for not RTFMing in the larger sense it would have helped - had I not stumbled over this issue I'd just have left a problematic version up.

**Comment by tarcieri** [comment]
@Licenser thanks for the feedback! Hopefully #118 addresses your concerns

**Comment by Licenser** [comment]
Thanks! That’s perfect
