### ISSUE TITLE
`office` crate has soundness issue & unmaintained

### ISSUE THREAD

**Issue by JOE1994** [RustSec/advisory-db#742]
[`office` crate](https://crates.io/crates/office) has the exact same issue as https://github.com/tafia/calamine/issues/199
in https://docs.rs/crate/office/0.8.1/source/src/cfb.rs (lines 175~184).

`office` crate's `repository` link leads to the github repo of the `calamine` crate.
`office` crate seems to be an older & unmaintained version of `calamine`.

**Comment by Shnatsel** [comment]
Can you get clarification on this situation from office/calamine upstream? We're happy to carry advisories for both the vulnerability and the unmaintained status if there's no way to issue a new release.

**Comment by Qwaz** [comment]
The description of `office` crate on crates.io says ([link](https://crates.io/search?q=office)):
> See 'calamine' crate. Contact me for 'office' ownership

Having said that, I believe checking with the upstream is always encouraged.
cc @tafia, could you kindly confirm that the users of `office` crate are expected to use `calamine` instead?

**Comment by tafia** [comment]
I confirm that the office crate is NOT supported and has long since been replaced by calamine.
