### ISSUE TITLE
`informational` field is undocumented

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/advisory-db#751]
We do not have the `informational` field in the advisory template, which leads to confusion for reporters (see e.g. #750).

**Comment by tarcieri** [comment]
It's documented in `rustdoc` (which, in general, probably provides the most detailed documentation for the entire advisory format):

https://docs.rs/rustsec/0.23.0/rustsec/advisory/informational/enum.Informational.html

However it'd be good to link this in the comments on the advisory template, along with a short synopsis.

**Comment by pinkforest** [comment]
https://github.com/rustsec/advisory-db/pull/1341 clarified on this in the example

This was also discussed in zulip that led to that PR - closing this as Resolved
