### ISSUE TITLE
RSS feed gone since 2021-03-06

### ISSUE THREAD

**Issue by jfrimmel** [RustSec/advisory-db#825]
I'm not sure, whether this is a bug or the intended behavior:

I've subscribed to the RSS feed of the advisories, which was available under this link: [https://github.com/RustSec/advisory-db](https://github.com/RustSec/advisory-db). I've received updates until _RUSTSEC-2021-0037_, but since then the feed seems to be gone.

Was the feed moved to another location or was it removed intentionally?

**Comment by tarcieri** [comment]
We recently migrated off of Jekyll and onto an all-Rust rendering solution for the site in https://github.com/RustSec/rustsec-admin/pull/115

As part of that we lost the RSS feed. We weren't sure if anyone was actually using it, although now we have an answer to that.

We could potentially add it back /cc @ammaraskar

**Comment by oherrala** [comment]
I'll raise my hand also! We are following multiple vulnerability feeds via RSS/Atom in a single Slack channel. RustSec feed would be really useful.

**Comment by amousset** [comment]
I've started working on adding it back!

**Comment by tarcieri** [comment]
It's back! 🎉 

https://rustsec.org/feed.xml
