### ISSUE TITLE
`spin` looks like it is maintained again

### ISSUE THREAD

**Issue by silwol** [RustSec/advisory-db#830]
In contrary to what https://rustsec.org/advisories/RUSTSEC-2019-0031.html says, it looks like the `spin` crate is maintained again, with regular updates somewhere around once per month, sometimes longer, sometimes shorter, over half a year. Looks like an additional maintainer https://github.com/zesterer joined the project, who has been active over several years and is well-known for being one of the https://veloren.net/ founders and active members.

**Comment by tarcieri** [comment]
We "yanked" this advisory in #423 which means `cargo audit` should no longer generate a warning for it, but also recently switched to a new website renderer which isn't displaying any information to indicate that the advisory is no-longer valid.

In cases like this we should display text to the effect of "This advisory has been yanked and is no longer relevant" on the web site, and ideally link to the raw advisory (#556) if people are curious about the details of the original advisory.

**Comment by silwol** [comment]
Thanks for the clarification. In that case, the database already reflects the status as expected and it's just a presentation issue. For reference: I re-visited the page through the deep link from https://bugs.debian.org/946921 so I'd expect it to be available there, bu with the additional information that it's no longer valid, as you described.
