### ISSUE TITLE
`cargo-crev` integration?

### ISSUE THREAD

**Issue by dpc** [RustSec/advisory-db#85]
I was just reading https://snf.github.io/2019/01/10/rust-2019-security/ and I was wondering what would be the best way to integrate advisory-db   with [`cargo crev`](https://github.com/dpc/crev/tree/master/cargo-crev). The most natural way seems to be to have official `advisory-db` CrevId. It seems like advisory format fits quite well into crev's Package Review Proof format.

We could start by preparing a converter from the existing format to crev proofs. 

Would there be a will to integrate these two projects? If there was, I could "hardcode"/auto-suggest such an Id to all users of `cargo-crev`. If not, I guess I could run such an Id as a part of `crev` project too.

Please let me know your thoughts!

**Comment by tarcieri** [comment]
I'd be happy to find a way to integrate this with `cargo crev`, particularly if you just want to ingest the advisories into a format it understands.

**Comment by dpc** [comment]
I think continuously converting all *Advisories* into *Package ReviewProos* with `rating: dangerous` would be a best way to go. If we have a such a way, would you like to host and maintain a CrevId and Proof Repository as part of `advisory-db`? I guess it would be just running a cronjob over a small cli tool that ingests all *Advisories* and publishes them as *Package ReviewProos*.

**Comment by tarcieri** [comment]
It's something I can look into, but there's a lot of other lower hanging fruit for RustSec I'd consider to be higher priority.

If you'd like to run it as part of the `cargo crev` project, that'd also be fine by me.

**Comment by dpc** [comment]
Thanks! We'll look into it then and let you know when we have something. :)

**Comment by dpc** [comment]
I have completed https://github.com/dpc/crev/issues/149 by just adding a way to mark specific crate versions as containing an important fix / advisory. 

For starter I've manually reported all advisories under my own identity: https://github.com/dpc/crev-proofs/blob/master/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/reviews/2019-04-packages-Ua7DxQ.proof.crev

I think it should be a good start.

**Comment by tarcieri** [comment]
Sounds good @dpc ! Should we close this issue, or was there something else you had in mind?
